### ISSUE TITLE
Can't pass an empty "properties" object

### ISSUE THREAD

**Issue by davidebbo** [suwatch/ManagePortal#4]
Sometimes, everything in 'properties' is optional, so we'd like to pass:

```json
{
    "properties": { }
}
```

But it ends up optimizing it out, failing the request.

Maybe it should only yank simple properties that have a place holder value like "(string)", but it should not remove empty objects?

**Comment by ahmelsayed** [comment]
the problem is that we sometimes add complex objects that are also totally empty.
This for example:

```json
"connectionStrings": [
    {
        "connectionString": "(string)",
        "name": "(string)",
        "type": "(MySql|SQLServer|SQLAzure|Custom)"
    }
]
```

when we clean the connection string object, we are left with an empty object in the array, so we just remove that object, which leaves us with an empty array, so we remove that as well.

I am not sure how CSM endpoint will handle existing but empty arrays or objects

**Comment by davidebbo** [comment]
I would expect an empty conn string array to be perfectly valid for ARM

**Comment by davidebbo** [comment]
BTW, note that in 2014-11-01, connection strings are no longer using arrays, and instead look like:

```
{ 
  "properties": {
    "foo": { "Value": "SomeValue", "Type": 0 }
  }
} 
```

Of course, there could still be arrays in other places.

**Comment by ahmelsayed** [comment]
there is a problem with not top level arrays and objects.

in this for example

```json
"virtualApplications": [
    {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": false,
        "virtualDirectories": null
    },
    {
        "virtualPath": "(string)",
        "physicalPath": "(string)",
        "preloadEnabled": "(boolean)",
        "virtualDirectories": [
            {
                "virtualPath": "(string)",
                "physicalPath": "(string)"
            }
        ]
    }
]
```

we clean up the `"virtualDirectories"` array and then leave it empty, so since the first object in `"vistualApplications"` array is not empty, we don't remove it.
After the clean-up we end up with an object like this

```json
"virtualApplications": [
    {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": false,
        "virtualDirectories": null
    },
    {
        "virtualDirectories": [   ]
    }
]
```

and putting that fails for some reason with an odd error message

**Comment by davidebbo** [comment]
Ok, seems only sane way is to special case the top level `"properties"`. If it's not there in the PUT body after the cleanup sequence, add it with an empty object value.
